Repository mct-joken/mct-student-association, pull requests merged in 2023-05, with the labels that each got.

#10 feat: readmeの内容を更新
  README.md
  docs/CONTRIBUTING.md
Labels: enhancement

#18 fix: pnpm-lock.jsonが壊れている問題を修正
  pnpm-lock.yaml
Labels: bug

#21 feat: パッケージマネージャーをpnpmに限定
  README.md
  docs/CONTRIBUTING.md
  package.json
Labels: documentation, enhancement

#33 fix(ui): ヘッダーのスペースを改善
  src/css/Header/narrowHeader.module.css
  src/css/Header/wideHeader.module.css
Labels: enhancement
